service: dataService
# app and org for use with dashboard.serverless.com
#app: mrkt-backend
#org: mrkt

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
          - dynamodb:PutItem
        Resource: "*"
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  fetch_external:
    handler: bin/fetch_external
  post_ddb:
    handler: bin/post_ddb
stepFunctions:
  stateMachines:
    dataCollection:
      definition:
        Comment: "Initialize step to fetch data from external api and post into ddb"
        StartAt: FetchLambda
        States:
          FetchLambda:
            Type: Task
            Resource:
              Fn::GetAtt: [fetch_external, Arn]
            Next: PostLambda
          PostLambda:
            Type: Task
            Resource:
              Fn::GetAtt: [post_ddb, Arn]
            End: true
plugins:
  - serverless-step-functions
