service: dataService
# app and org for use with dashboard.serverless.com
#app: mrkt-backend
#org: mrkt

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
          - dynamodb:PutItem
        Resource: "*"
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  post_ticker_sqs:
    handler: bin/post_ticker_sqs
  fetch_ticker:
    handler: bin/fetch_ticker
  initialize_step_function:
    handler: bin/initialize_step_function
    events:
        - sqs: arn:aws:sqs:us-west-2:115333527451:ticker-data-collection
  post_ddb:
    handler: bin/post_ddb
stepFunctions:
  stateMachines:
    dataCollection:
      definition:
        Comment: "Initialize step to fetch data from external api and post into ddb"
        StartAt: FETCH_TICKER
        States:
          FETCH_TICKER:
            Type: Task
            Resource:
              Fn::GetAtt: [fetch_ticker, Arn]
            Next: POST_DDB
          POST_DDB:
            Type: Task
            Resource:
              Fn::GetAtt: [post_ddb, Arn]
            End: true
plugins:
  - serverless-step-functions
